language: python

matrix:
    include:
        - os: linux
          python: 2.6

        - os: linux
          sudo: required
          python: 2.6
          env:
            - CAN_SUDO=true

        - os: linux
          sudo: required
          python: 2.6
          env:
            - CAN_SUDO=true
            - DO_PCAPDNET=true

        - os: osx
          language: generic

        - os: osx
          language: generic
          env:
            - CAN_SUDO=true
            - DO_PCAPDNET=true

        - os: osx
          language: generic
          env: PYTHON=3.6.4

before_install: sh .travis/osx_py3.sh

install: sh .travis/install.sh

script: sh .travis/test.sh
