language: python

matrix:
    include:
        - os: linux
          python: 2.6

        - os: linux
          sudo: required
          python: 2.6
          env: CAN_SUDO=true

        - os: osx
          language: generic

script: sh test.sh
